# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f4912c3a37d562bee42769371a2720a7bedffc92b84d6dabe0667e96674fba8954caefa5053b2e135d1d7b4d45daea4e3cf599c7e961f13ee9b66f8b7aa4689

test:
  secret_key_base: 1450fc5f799cb38c5e865c3be7fce2a72c4a09415dd15fb7849ad7f2a0865f3dcd078bc6237674ef2c95d9c053096218751b3a6b0ac71fbe3411b558fa88dea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
